//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("QUANLYBANVOTModel", "FK__DonHang__MaKhach__2B3F6F97", "KhachHang", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DVH.QLBVot.Models.KhachHang), "DonHang", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DVH.QLBVot.Models.DonHang), true)]
[assembly: EdmRelationshipAttribute("QUANLYBANVOTModel", "FK__HoaDon__MaDonHan__33D4B598", "DonHang", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DVH.QLBVot.Models.DonHang), "HoaDon", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DVH.QLBVot.Models.HoaDon), true)]
[assembly: EdmRelationshipAttribute("QUANLYBANVOTModel", "FK__Vot__MaNhaCungCa__286302EC", "NhaCungCap", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DVH.QLBVot.Models.NhaCungCap), "Vot", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DVH.QLBVot.Models.Vot), true)]

#endregion

namespace DVH.QLBVot.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class QUANLYBANVOTEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new QUANLYBANVOTEntities1 object using the connection string found in the 'QUANLYBANVOTEntities1' section of the application configuration file.
        /// </summary>
        public QUANLYBANVOTEntities1() : base("name=QUANLYBANVOTEntities1", "QUANLYBANVOTEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QUANLYBANVOTEntities1 object.
        /// </summary>
        public QUANLYBANVOTEntities1(string connectionString) : base(connectionString, "QUANLYBANVOTEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QUANLYBANVOTEntities1 object.
        /// </summary>
        public QUANLYBANVOTEntities1(EntityConnection connection) : base(connection, "QUANLYBANVOTEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DonHang> DonHangs
        {
            get
            {
                if ((_DonHangs == null))
                {
                    _DonHangs = base.CreateObjectSet<DonHang>("DonHangs");
                }
                return _DonHangs;
            }
        }
        private ObjectSet<DonHang> _DonHangs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HoaDon> HoaDons
        {
            get
            {
                if ((_HoaDons == null))
                {
                    _HoaDons = base.CreateObjectSet<HoaDon>("HoaDons");
                }
                return _HoaDons;
            }
        }
        private ObjectSet<HoaDon> _HoaDons;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<KhachHang> KhachHangs
        {
            get
            {
                if ((_KhachHangs == null))
                {
                    _KhachHangs = base.CreateObjectSet<KhachHang>("KhachHangs");
                }
                return _KhachHangs;
            }
        }
        private ObjectSet<KhachHang> _KhachHangs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NhaCungCap> NhaCungCaps
        {
            get
            {
                if ((_NhaCungCaps == null))
                {
                    _NhaCungCaps = base.CreateObjectSet<NhaCungCap>("NhaCungCaps");
                }
                return _NhaCungCaps;
            }
        }
        private ObjectSet<NhaCungCap> _NhaCungCaps;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TaiKhoan> TaiKhoans
        {
            get
            {
                if ((_TaiKhoans == null))
                {
                    _TaiKhoans = base.CreateObjectSet<TaiKhoan>("TaiKhoans");
                }
                return _TaiKhoans;
            }
        }
        private ObjectSet<TaiKhoan> _TaiKhoans;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Vot> Vots
        {
            get
            {
                if ((_Vots == null))
                {
                    _Vots = base.CreateObjectSet<Vot>("Vots");
                }
                return _Vots;
            }
        }
        private ObjectSet<Vot> _Vots;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DonHangs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDonHangs(DonHang donHang)
        {
            base.AddObject("DonHangs", donHang);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HoaDons EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHoaDons(HoaDon hoaDon)
        {
            base.AddObject("HoaDons", hoaDon);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the KhachHangs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKhachHangs(KhachHang khachHang)
        {
            base.AddObject("KhachHangs", khachHang);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NhaCungCaps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNhaCungCaps(NhaCungCap nhaCungCap)
        {
            base.AddObject("NhaCungCaps", nhaCungCap);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TaiKhoans EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTaiKhoans(TaiKhoan taiKhoan)
        {
            base.AddObject("TaiKhoans", taiKhoan);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Vots EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVots(Vot vot)
        {
            base.AddObject("Vots", vot);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QUANLYBANVOTModel", Name="DonHang")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DonHang : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DonHang object.
        /// </summary>
        /// <param name="maDonHang">Initial value of the MaDonHang property.</param>
        /// <param name="ngayDatHang">Initial value of the NgayDatHang property.</param>
        /// <param name="tongTien">Initial value of the TongTien property.</param>
        public static DonHang CreateDonHang(global::System.Int32 maDonHang, global::System.DateTime ngayDatHang, global::System.Double tongTien)
        {
            DonHang donHang = new DonHang();
            donHang.MaDonHang = maDonHang;
            donHang.NgayDatHang = ngayDatHang;
            donHang.TongTien = tongTien;
            return donHang;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaDonHang
        {
            get
            {
                return _MaDonHang;
            }
            set
            {
                if (_MaDonHang != value)
                {
                    OnMaDonHangChanging(value);
                    ReportPropertyChanging("MaDonHang");
                    _MaDonHang = StructuralObject.SetValidValue(value, "MaDonHang");
                    ReportPropertyChanged("MaDonHang");
                    OnMaDonHangChanged();
                }
            }
        }
        private global::System.Int32 _MaDonHang;
        partial void OnMaDonHangChanging(global::System.Int32 value);
        partial void OnMaDonHangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaKhachHang
        {
            get
            {
                return _MaKhachHang;
            }
            set
            {
                OnMaKhachHangChanging(value);
                ReportPropertyChanging("MaKhachHang");
                _MaKhachHang = StructuralObject.SetValidValue(value, "MaKhachHang");
                ReportPropertyChanged("MaKhachHang");
                OnMaKhachHangChanged();
            }
        }
        private Nullable<global::System.Int32> _MaKhachHang;
        partial void OnMaKhachHangChanging(Nullable<global::System.Int32> value);
        partial void OnMaKhachHangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime NgayDatHang
        {
            get
            {
                return _NgayDatHang;
            }
            set
            {
                OnNgayDatHangChanging(value);
                ReportPropertyChanging("NgayDatHang");
                _NgayDatHang = StructuralObject.SetValidValue(value, "NgayDatHang");
                ReportPropertyChanged("NgayDatHang");
                OnNgayDatHangChanged();
            }
        }
        private global::System.DateTime _NgayDatHang;
        partial void OnNgayDatHangChanging(global::System.DateTime value);
        partial void OnNgayDatHangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double TongTien
        {
            get
            {
                return _TongTien;
            }
            set
            {
                OnTongTienChanging(value);
                ReportPropertyChanging("TongTien");
                _TongTien = StructuralObject.SetValidValue(value, "TongTien");
                ReportPropertyChanged("TongTien");
                OnTongTienChanged();
            }
        }
        private global::System.Double _TongTien;
        partial void OnTongTienChanging(global::System.Double value);
        partial void OnTongTienChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QUANLYBANVOTModel", "FK__DonHang__MaKhach__2B3F6F97", "KhachHang")]
        public KhachHang KhachHang
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<KhachHang>("QUANLYBANVOTModel.FK__DonHang__MaKhach__2B3F6F97", "KhachHang").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<KhachHang>("QUANLYBANVOTModel.FK__DonHang__MaKhach__2B3F6F97", "KhachHang").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<KhachHang> KhachHangReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<KhachHang>("QUANLYBANVOTModel.FK__DonHang__MaKhach__2B3F6F97", "KhachHang");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<KhachHang>("QUANLYBANVOTModel.FK__DonHang__MaKhach__2B3F6F97", "KhachHang", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QUANLYBANVOTModel", "FK__HoaDon__MaDonHan__33D4B598", "HoaDon")]
        public EntityCollection<HoaDon> HoaDons
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<HoaDon>("QUANLYBANVOTModel.FK__HoaDon__MaDonHan__33D4B598", "HoaDon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<HoaDon>("QUANLYBANVOTModel.FK__HoaDon__MaDonHan__33D4B598", "HoaDon", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QUANLYBANVOTModel", Name="HoaDon")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HoaDon : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HoaDon object.
        /// </summary>
        /// <param name="maHoaDon">Initial value of the MaHoaDon property.</param>
        /// <param name="ngayLap">Initial value of the NgayLap property.</param>
        /// <param name="tongTien">Initial value of the TongTien property.</param>
        public static HoaDon CreateHoaDon(global::System.Int32 maHoaDon, global::System.DateTime ngayLap, global::System.Double tongTien)
        {
            HoaDon hoaDon = new HoaDon();
            hoaDon.MaHoaDon = maHoaDon;
            hoaDon.NgayLap = ngayLap;
            hoaDon.TongTien = tongTien;
            return hoaDon;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaHoaDon
        {
            get
            {
                return _MaHoaDon;
            }
            set
            {
                if (_MaHoaDon != value)
                {
                    OnMaHoaDonChanging(value);
                    ReportPropertyChanging("MaHoaDon");
                    _MaHoaDon = StructuralObject.SetValidValue(value, "MaHoaDon");
                    ReportPropertyChanged("MaHoaDon");
                    OnMaHoaDonChanged();
                }
            }
        }
        private global::System.Int32 _MaHoaDon;
        partial void OnMaHoaDonChanging(global::System.Int32 value);
        partial void OnMaHoaDonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaDonHang
        {
            get
            {
                return _MaDonHang;
            }
            set
            {
                OnMaDonHangChanging(value);
                ReportPropertyChanging("MaDonHang");
                _MaDonHang = StructuralObject.SetValidValue(value, "MaDonHang");
                ReportPropertyChanged("MaDonHang");
                OnMaDonHangChanged();
            }
        }
        private Nullable<global::System.Int32> _MaDonHang;
        partial void OnMaDonHangChanging(Nullable<global::System.Int32> value);
        partial void OnMaDonHangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime NgayLap
        {
            get
            {
                return _NgayLap;
            }
            set
            {
                OnNgayLapChanging(value);
                ReportPropertyChanging("NgayLap");
                _NgayLap = StructuralObject.SetValidValue(value, "NgayLap");
                ReportPropertyChanged("NgayLap");
                OnNgayLapChanged();
            }
        }
        private global::System.DateTime _NgayLap;
        partial void OnNgayLapChanging(global::System.DateTime value);
        partial void OnNgayLapChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double TongTien
        {
            get
            {
                return _TongTien;
            }
            set
            {
                OnTongTienChanging(value);
                ReportPropertyChanging("TongTien");
                _TongTien = StructuralObject.SetValidValue(value, "TongTien");
                ReportPropertyChanged("TongTien");
                OnTongTienChanged();
            }
        }
        private global::System.Double _TongTien;
        partial void OnTongTienChanging(global::System.Double value);
        partial void OnTongTienChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QUANLYBANVOTModel", "FK__HoaDon__MaDonHan__33D4B598", "DonHang")]
        public DonHang DonHang
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DonHang>("QUANLYBANVOTModel.FK__HoaDon__MaDonHan__33D4B598", "DonHang").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DonHang>("QUANLYBANVOTModel.FK__HoaDon__MaDonHan__33D4B598", "DonHang").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DonHang> DonHangReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DonHang>("QUANLYBANVOTModel.FK__HoaDon__MaDonHan__33D4B598", "DonHang");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DonHang>("QUANLYBANVOTModel.FK__HoaDon__MaDonHan__33D4B598", "DonHang", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QUANLYBANVOTModel", Name="KhachHang")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class KhachHang : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new KhachHang object.
        /// </summary>
        /// <param name="maKhachHang">Initial value of the MaKhachHang property.</param>
        /// <param name="tenKhachHang">Initial value of the TenKhachHang property.</param>
        public static KhachHang CreateKhachHang(global::System.Int32 maKhachHang, global::System.String tenKhachHang)
        {
            KhachHang khachHang = new KhachHang();
            khachHang.MaKhachHang = maKhachHang;
            khachHang.TenKhachHang = tenKhachHang;
            return khachHang;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaKhachHang
        {
            get
            {
                return _MaKhachHang;
            }
            set
            {
                if (_MaKhachHang != value)
                {
                    OnMaKhachHangChanging(value);
                    ReportPropertyChanging("MaKhachHang");
                    _MaKhachHang = StructuralObject.SetValidValue(value, "MaKhachHang");
                    ReportPropertyChanged("MaKhachHang");
                    OnMaKhachHangChanged();
                }
            }
        }
        private global::System.Int32 _MaKhachHang;
        partial void OnMaKhachHangChanging(global::System.Int32 value);
        partial void OnMaKhachHangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TenKhachHang
        {
            get
            {
                return _TenKhachHang;
            }
            set
            {
                OnTenKhachHangChanging(value);
                ReportPropertyChanging("TenKhachHang");
                _TenKhachHang = StructuralObject.SetValidValue(value, false, "TenKhachHang");
                ReportPropertyChanged("TenKhachHang");
                OnTenKhachHangChanged();
            }
        }
        private global::System.String _TenKhachHang;
        partial void OnTenKhachHangChanging(global::System.String value);
        partial void OnTenKhachHangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DiaChi
        {
            get
            {
                return _DiaChi;
            }
            set
            {
                OnDiaChiChanging(value);
                ReportPropertyChanging("DiaChi");
                _DiaChi = StructuralObject.SetValidValue(value, true, "DiaChi");
                ReportPropertyChanged("DiaChi");
                OnDiaChiChanged();
            }
        }
        private global::System.String _DiaChi;
        partial void OnDiaChiChanging(global::System.String value);
        partial void OnDiaChiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SoDienThoai
        {
            get
            {
                return _SoDienThoai;
            }
            set
            {
                OnSoDienThoaiChanging(value);
                ReportPropertyChanging("SoDienThoai");
                _SoDienThoai = StructuralObject.SetValidValue(value, true, "SoDienThoai");
                ReportPropertyChanged("SoDienThoai");
                OnSoDienThoaiChanged();
            }
        }
        private global::System.String _SoDienThoai;
        partial void OnSoDienThoaiChanging(global::System.String value);
        partial void OnSoDienThoaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QUANLYBANVOTModel", "FK__DonHang__MaKhach__2B3F6F97", "DonHang")]
        public EntityCollection<DonHang> DonHangs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DonHang>("QUANLYBANVOTModel.FK__DonHang__MaKhach__2B3F6F97", "DonHang");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DonHang>("QUANLYBANVOTModel.FK__DonHang__MaKhach__2B3F6F97", "DonHang", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QUANLYBANVOTModel", Name="NhaCungCap")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NhaCungCap : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NhaCungCap object.
        /// </summary>
        /// <param name="maNhaCungCap">Initial value of the MaNhaCungCap property.</param>
        /// <param name="tenNhaCungCap">Initial value of the TenNhaCungCap property.</param>
        public static NhaCungCap CreateNhaCungCap(global::System.Int32 maNhaCungCap, global::System.String tenNhaCungCap)
        {
            NhaCungCap nhaCungCap = new NhaCungCap();
            nhaCungCap.MaNhaCungCap = maNhaCungCap;
            nhaCungCap.TenNhaCungCap = tenNhaCungCap;
            return nhaCungCap;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaNhaCungCap
        {
            get
            {
                return _MaNhaCungCap;
            }
            set
            {
                if (_MaNhaCungCap != value)
                {
                    OnMaNhaCungCapChanging(value);
                    ReportPropertyChanging("MaNhaCungCap");
                    _MaNhaCungCap = StructuralObject.SetValidValue(value, "MaNhaCungCap");
                    ReportPropertyChanged("MaNhaCungCap");
                    OnMaNhaCungCapChanged();
                }
            }
        }
        private global::System.Int32 _MaNhaCungCap;
        partial void OnMaNhaCungCapChanging(global::System.Int32 value);
        partial void OnMaNhaCungCapChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TenNhaCungCap
        {
            get
            {
                return _TenNhaCungCap;
            }
            set
            {
                OnTenNhaCungCapChanging(value);
                ReportPropertyChanging("TenNhaCungCap");
                _TenNhaCungCap = StructuralObject.SetValidValue(value, false, "TenNhaCungCap");
                ReportPropertyChanged("TenNhaCungCap");
                OnTenNhaCungCapChanged();
            }
        }
        private global::System.String _TenNhaCungCap;
        partial void OnTenNhaCungCapChanging(global::System.String value);
        partial void OnTenNhaCungCapChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DiaChi
        {
            get
            {
                return _DiaChi;
            }
            set
            {
                OnDiaChiChanging(value);
                ReportPropertyChanging("DiaChi");
                _DiaChi = StructuralObject.SetValidValue(value, true, "DiaChi");
                ReportPropertyChanged("DiaChi");
                OnDiaChiChanged();
            }
        }
        private global::System.String _DiaChi;
        partial void OnDiaChiChanging(global::System.String value);
        partial void OnDiaChiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SoDienThoai
        {
            get
            {
                return _SoDienThoai;
            }
            set
            {
                OnSoDienThoaiChanging(value);
                ReportPropertyChanging("SoDienThoai");
                _SoDienThoai = StructuralObject.SetValidValue(value, true, "SoDienThoai");
                ReportPropertyChanged("SoDienThoai");
                OnSoDienThoaiChanged();
            }
        }
        private global::System.String _SoDienThoai;
        partial void OnSoDienThoaiChanging(global::System.String value);
        partial void OnSoDienThoaiChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QUANLYBANVOTModel", "FK__Vot__MaNhaCungCa__286302EC", "Vot")]
        public EntityCollection<Vot> Vots
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Vot>("QUANLYBANVOTModel.FK__Vot__MaNhaCungCa__286302EC", "Vot");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Vot>("QUANLYBANVOTModel.FK__Vot__MaNhaCungCa__286302EC", "Vot", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QUANLYBANVOTModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value, "principal_id");
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value, "diagram_id");
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value, "version");
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true, "definition");
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QUANLYBANVOTModel", Name="TaiKhoan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TaiKhoan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TaiKhoan object.
        /// </summary>
        /// <param name="tenDangNhap">Initial value of the TenDangNhap property.</param>
        public static TaiKhoan CreateTaiKhoan(global::System.String tenDangNhap)
        {
            TaiKhoan taiKhoan = new TaiKhoan();
            taiKhoan.TenDangNhap = tenDangNhap;
            return taiKhoan;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TenDangNhap
        {
            get
            {
                return _TenDangNhap;
            }
            set
            {
                if (_TenDangNhap != value)
                {
                    OnTenDangNhapChanging(value);
                    ReportPropertyChanging("TenDangNhap");
                    _TenDangNhap = StructuralObject.SetValidValue(value, false, "TenDangNhap");
                    ReportPropertyChanged("TenDangNhap");
                    OnTenDangNhapChanged();
                }
            }
        }
        private global::System.String _TenDangNhap;
        partial void OnTenDangNhapChanging(global::System.String value);
        partial void OnTenDangNhapChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MatKhau
        {
            get
            {
                return _MatKhau;
            }
            set
            {
                OnMatKhauChanging(value);
                ReportPropertyChanging("MatKhau");
                _MatKhau = StructuralObject.SetValidValue(value, true, "MatKhau");
                ReportPropertyChanged("MatKhau");
                OnMatKhauChanged();
            }
        }
        private global::System.String _MatKhau;
        partial void OnMatKhauChanging(global::System.String value);
        partial void OnMatKhauChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenHienThi
        {
            get
            {
                return _TenHienThi;
            }
            set
            {
                OnTenHienThiChanging(value);
                ReportPropertyChanging("TenHienThi");
                _TenHienThi = StructuralObject.SetValidValue(value, true, "TenHienThi");
                ReportPropertyChanged("TenHienThi");
                OnTenHienThiChanged();
            }
        }
        private global::System.String _TenHienThi;
        partial void OnTenHienThiChanging(global::System.String value);
        partial void OnTenHienThiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SoDienThoai
        {
            get
            {
                return _SoDienThoai;
            }
            set
            {
                OnSoDienThoaiChanging(value);
                ReportPropertyChanging("SoDienThoai");
                _SoDienThoai = StructuralObject.SetValidValue(value, true, "SoDienThoai");
                ReportPropertyChanged("SoDienThoai");
                OnSoDienThoaiChanged();
            }
        }
        private global::System.String _SoDienThoai;
        partial void OnSoDienThoaiChanging(global::System.String value);
        partial void OnSoDienThoaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value, "Active");
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _Active;
        partial void OnActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnActiveChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QUANLYBANVOTModel", Name="Vot")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Vot : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Vot object.
        /// </summary>
        /// <param name="maVot">Initial value of the MaVot property.</param>
        /// <param name="tenVot">Initial value of the TenVot property.</param>
        /// <param name="gia">Initial value of the Gia property.</param>
        public static Vot CreateVot(global::System.Int32 maVot, global::System.String tenVot, global::System.Double gia)
        {
            Vot vot = new Vot();
            vot.MaVot = maVot;
            vot.TenVot = tenVot;
            vot.Gia = gia;
            return vot;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaVot
        {
            get
            {
                return _MaVot;
            }
            set
            {
                if (_MaVot != value)
                {
                    OnMaVotChanging(value);
                    ReportPropertyChanging("MaVot");
                    _MaVot = StructuralObject.SetValidValue(value, "MaVot");
                    ReportPropertyChanged("MaVot");
                    OnMaVotChanged();
                }
            }
        }
        private global::System.Int32 _MaVot;
        partial void OnMaVotChanging(global::System.Int32 value);
        partial void OnMaVotChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TenVot
        {
            get
            {
                return _TenVot;
            }
            set
            {
                OnTenVotChanging(value);
                ReportPropertyChanging("TenVot");
                _TenVot = StructuralObject.SetValidValue(value, false, "TenVot");
                ReportPropertyChanged("TenVot");
                OnTenVotChanged();
            }
        }
        private global::System.String _TenVot;
        partial void OnTenVotChanging(global::System.String value);
        partial void OnTenVotChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LoaiVot
        {
            get
            {
                return _LoaiVot;
            }
            set
            {
                OnLoaiVotChanging(value);
                ReportPropertyChanging("LoaiVot");
                _LoaiVot = StructuralObject.SetValidValue(value, true, "LoaiVot");
                ReportPropertyChanged("LoaiVot");
                OnLoaiVotChanged();
            }
        }
        private global::System.String _LoaiVot;
        partial void OnLoaiVotChanging(global::System.String value);
        partial void OnLoaiVotChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Gia
        {
            get
            {
                return _Gia;
            }
            set
            {
                OnGiaChanging(value);
                ReportPropertyChanging("Gia");
                _Gia = StructuralObject.SetValidValue(value, "Gia");
                ReportPropertyChanged("Gia");
                OnGiaChanged();
            }
        }
        private global::System.Double _Gia;
        partial void OnGiaChanging(global::System.Double value);
        partial void OnGiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaNhaCungCap
        {
            get
            {
                return _MaNhaCungCap;
            }
            set
            {
                OnMaNhaCungCapChanging(value);
                ReportPropertyChanging("MaNhaCungCap");
                _MaNhaCungCap = StructuralObject.SetValidValue(value, "MaNhaCungCap");
                ReportPropertyChanged("MaNhaCungCap");
                OnMaNhaCungCapChanged();
            }
        }
        private Nullable<global::System.Int32> _MaNhaCungCap;
        partial void OnMaNhaCungCapChanging(Nullable<global::System.Int32> value);
        partial void OnMaNhaCungCapChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QUANLYBANVOTModel", "FK__Vot__MaNhaCungCa__286302EC", "NhaCungCap")]
        public NhaCungCap NhaCungCap
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NhaCungCap>("QUANLYBANVOTModel.FK__Vot__MaNhaCungCa__286302EC", "NhaCungCap").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NhaCungCap>("QUANLYBANVOTModel.FK__Vot__MaNhaCungCa__286302EC", "NhaCungCap").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<NhaCungCap> NhaCungCapReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NhaCungCap>("QUANLYBANVOTModel.FK__Vot__MaNhaCungCa__286302EC", "NhaCungCap");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<NhaCungCap>("QUANLYBANVOTModel.FK__Vot__MaNhaCungCa__286302EC", "NhaCungCap", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
