//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVH.QLBVot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public int MaChiTietDonHang { get; set; }
        public Nullable<int> MaDonHang { get; set; }
        public Nullable<int> MaVot { get; set; }
        public int SoLuong { get; set; }
        public double Gia { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual Vot Vot { get; set; }
    }
}
