//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVH.QLBVot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int MaHoaDon { get; set; }
        public Nullable<int> MaDonHang { get; set; }
        public System.DateTime NgayLap { get; set; }
        public double TongTien { get; set; }
    
        public virtual DonHang DonHang { get; set; }
    }
}
